config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "users#index"
  get "/coupon", to: "coupons#index"
  
  resources :users, only: [:create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  resources :coupons, only: [] do
    collection do
      get :change
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  before_create :encrypt_password

  def self.login(options)
    if options[:email] && options[:password]
      find_by(email: options[:email],
              password: Digest::SHA1.hexdigest("x" + options[:password] + "y"))
    end
  end

  private
  def encrypt_password
    self.password = bigbang(self.password)
  end

  def bigbang(string)
    string = "x" + string + "y"
    Digest::SHA1.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_in
    @user = User.new
  end

  def login
    user = User.login(user_params)

    if user
      sign_in_user(user)
      redirect_to root_path, notice: "成功登入"
    else
      redirect_to sign_in_users_path, notice: "請輸入正確帳號密碼"
    end
  end

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # 登入
      sign_in_user(@user)
      redirect_to root_path, notice: '會員註冊成功'
    else
      render :sign_up
    end
  end

  private
  def sign_in_user(u)
    session[:user_token] = u.id
  end

  def user_params
    params.require(:user).permit(:name, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coupons/index.html.erb
<%= link_to 'use coupon', change_coupons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubytest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= link_to 'Sign_up',sign_up_users_path %>
<%= link_to 'Sign_in',sign_in_users_path %>

app/views/users/sign_in.html.erb
<h1>會員登入</h1>

<%= form_for(@user, url: login_users_path) do |form| %>
  <div class="fields">
    <%= form.label :email %>
    <%= form.text_field :email, placeholder: '請輸入 email' %>
  </div>

  <div class="fields">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit "登入" %>
<% end %>

app/views/users/sign_up.html.erb
<h1>會員註冊</h1>

<%= form_for(@user) do |form| %>
  <div class="fields">
    <%= form.label :name, "名稱" %>
    <%= form.text_field :name %>
  </div>

  <div class="fields">
    <%= form.label :password, "密碼" %>
    <%= form.password_field :password %>
  </div>

  <div class="fields">
    <%= form.label :email, "信箱" %>
    <%= form.email_field :email %>
  </div>

  <%= form.submit "註冊帳號" %>
<% end %>